### PR TITLE
Fix struct assignment: no memcpy with -nostdlib.

### PR DESCRIPTION
**Pull request by busykai**
This fixes link error for struct assignment introduced in 4af2f04bd2f.

Use `memcpy_s` instead of struct assignment.

The error seen on current master:
```
gcc <...> -o src/acrn-hypervisor/build/acrn.out -static -nostdlib
<...>
src/acrn-hypervisor/build/arch/x86/trusty.o: In function `setup_trusty_info':
src/acrn-hypervisor/arch/x86/trusty.c:297: undefined reference to `memcpy'
```

### CODE REVIEW

**Comment by busykai** [comment]
ok. on a side note, favoring the latest over the first might be not the most encouraging open source practice.

**Comment by anthonyzxu** [comment]
Agreed, I should go over all the PRs first. I didn't expect two PRs fixing the same issue. lesson learnt!
